### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by MrMitch** [facebook-csharp-sdk/facebook-winclient-sdk#62]
I am using the `1.0.1` version of the NuGet package and the examples provided in the [documentation](http://facebooksdk.net/docs/windows/controls/login-ui-control/) do not work anymore.

The `LoginButton` doesn't seem to have an `ApplicationId` property anymore, as weel as a `CurrentSession` property.

How can we migrate existing code that uses theses properties ?

**Comment by Charwaka** [comment]
Download old nuget package version it contains that application id

**Comment by MrMitch** [comment]
Can you point me to a specific version number ?
Also, is there a documentation explaining how to login a user with the lastest version of the package ?

**Comment by Charwaka** [comment]
Facebooksdk.net see old version which has downloaded most

-----Original Message-----

**Comment by sanjeevdwivedi** [comment]
You should update to the latest version. In the updated SDK, you can configure the appid in one place. See http://facebooksdk.net/docs/windows/config/ and how to login using http://facebooksdk.net/docs/windows/login/. I would not recommend using the old SDK. It has been significantly refactored and supports many more features. The source for the SDK contains fully functional samples for all the platforms.

Also, please ask such questions on stackoverflow so that everyone can benefit.
